name: Test Permissions

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Git Permissions
        run: |
          echo "Testing git permissions..."
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Test if we can read the repository
          git status
          echo "Git read permissions working"
          
          # Test if we can create a test branch
          git checkout -b test-permissions-$(date +%s)
          echo "test" > test-file.txt
          git add test-file.txt
          git commit -m "Test commit"
          
          # Try to push (this will fail but we can see the error)
          if git push origin test-permissions-$(date +%s); then
            echo "Git write permissions working"
          else
            echo "Git write permissions failed"
          fi

      - name: Test Issue Creation
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const { data: issue } = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Test Issue - ${new Date().toISOString()}`,
                body: `This is a test issue created by GitHub Actions to verify permissions.
                
                **Test Details:**
                - Workflow: ${context.workflow}
                - Run ID: ${context.runId}
                - Date: ${new Date().toISOString()}
                
                This issue can be safely deleted.`,
                labels: ['test', 'permissions-check']
              });
              console.log(`Issue creation working: ${issue.html_url}`);
            } catch (error) {
              console.log(`Issue creation failed: ${error.message}`);
            }
